DELETE FROM LOGGING_TRANSFORMATION_PDI
DELETE FROM LOGGING_STEP_PDI
DELETE FROM LOGGING_CHANNELS_PDI

SELECT * FROM LOGGING_JOB_PDI 
SELECT * FROM LOGGING_TRANSFORMATION_PDI
SELECT * FROM LOGGING_STEP_PDI
SELECT * FROM LOGGING_CHANNELS_PDI 

-- JOB OPERACION
SELECT J.ID_JOB,J.JOBNAME, T.* FROM LOGGING_CHANNELS_PDI AS C
INNER JOIN LOGGING_JOB_PDI AS J ON C.ROOT_CHANNEL_ID = J.CHANNEL_ID
WHERE  C.LOGGING_OBJECT_TYPE = 'TRANS'

-- JOB TRANSFORMANTION
SELECT J.ID_JOB,J.JOBNAME, T.* FROM LOGGING_CHANNELS_PDI AS C
INNER JOIN LOGGING_JOB_PDI AS J ON C.ROOT_CHANNEL_ID = J.CHANNEL_ID
INNER JOIN LOGGING_TRANSFORMATION_PDI AS T ON C.CHANNEL_ID = T.CHANNEL_ID
WHERE  C.LOGGING_OBJECT_TYPE = 'TRANS'

